import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Providers from '@/providers'
import Toaster from '@/components/Toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Shop App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark" className="transition-all">
      <body className={inter.className}>
        <Providers>
          <div className='flex min-h-screen flex-col justify-between'>
            <div>
              <Navbar></Navbar>
              <main>{children}</main>
            </div>
            <Footer></Footer>
          </div>
        </Providers>
        <Toaster></Toaster>
      </body>
    </html>
  )
}
